# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

test_that("importe_redevances_industrie works", {
   config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
 dossier <- system.file(package = "gwilenalim")
fichier0<-paste0(dossier, "/Industrie/TAB_Effluents_industriels_rejetes_11e_programme.xlsx")

    expect_true( importe_redevances_industrie(fichier0) == "OK")
})
