# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' importe_redevances_industrie
#' 
#' Fonction pour importer les données redevances industrielles de l'AELB disponibles sous https://donnees-documents.eau-loire-bretagne.fr/home/donnees/flux-de-pollution---industries.html
#' @param fihier : adresse du fichier où est stocké les fichiers xlsx dézippé depuis le site AELB
#' 
#' @return
#' statut de l'enregistrement des données (OK si les lignes ont été importées et KO sinon)
#' @export
#' @examples
#' config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
#'  dossier <- system.file(package = "gwilenalim")
#' fichier0<-paste0(dossier, "/Industrie/TAB_Effluents_industriels_rejetes_11e_programme.xlsx")
#'
#'  
#'  
#' importe_redevances_industrie(fichier0)
importe_redevances_industrie <- function(fichier){
   if (!is.character(fichier)) {stop("fichier should be character")}
  if(!file.exists(fichier)){stop("le fichier indiqué est absent")}
  if(!tools::file_ext(fichier)=="xlsx"){stop("le fichier doit être au format xlsx")}

# lecture du fichier et conversion en objet SF  
tryCatch({data <- readxl::read_excel(fichier, sheet = "Pollution produite")
names(data)<-tolower(names(data))
# Convertir les coordonnées Lambert 93 en un objet sf (simple features)
data <- sf::st_as_sf(data, coords = c("coord_x_rejet_principal", "coord_y_rejet_principal"), crs = 2154)
}, 
         error = function(e) {
    # Gérer les erreurs et afficher un message personnalisé
    message("Une erreur est survenue : ", e$message)
   "KO"
  })
         


  
# Établir la connexion à la base de données en utilisant les informations de connexion du fichier YAML
con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = config$host,
                      port = config$port,
                      user = config$user,
                      password = config$password,
                      dbname = config$dbname)
  

##### ENREGISTREMENT DU RESULTAT (DONNEES AELB) DANS GEOGWILEN #####
table_id <- DBI::Id(schema = "m621_step",
                          table = "flux_redevances_indus_aelb")

try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE m621_step.flux_redevances_indus_aelb (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(data)[colnames(data)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)

# Insérer l'objet sf dans la table postgis
sf::st_write(data, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE m621_step.flux_redevances_indus_aelb IS '{
  \"Title\": \"Flux annuels de pollution déclarés par les industriels assujettis à la redevance pollution de l’eau d’origine non domestique, sur le bassin Loire-Bretagne.\",
  \"Abstract\": \"Données extraites de https://donnees-documents.eau-loire-bretagne.fr/home/donnees/flux-de-pollution---industries.html pour le bassin Loire-Bretagne et importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"industrie\", \"assainissement\",\"redevance\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(data)$xmin,",
    \"ymin\": ",sf::st_bbox(data)$ymin,",
    \"xmax\": ",sf::st_bbox(data)$xmax,",
    \"ymax\": ",sf::st_bbox(data)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(data$annee_redevance),"\",
    \"End\": \"",max(data$annee_redevance),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://donnees-documents.eau-loire-bretagne.fr/home/donnees/flux-de-pollution---industries.html\"
  }]
}'"))


##### ENREGISTREMENT DU RESULTAT FILTRE SUR LE BASSIN DE LA VILAINE DANS GEOGWILEN #####

env_local <- new.env()
data("sage_vilaine", package = "gwilenalim", envir = env_local)

if (!"sage_vilaine" %in% ls(env_local)) {
  stop("L'objet 'sage_vilaine' n'a pas été trouvé dans le package.")
}

sage_vilaine <- env_local$sage_vilaine

sage_vilaine<-sf::st_transform(sage_vilaine, 2154)

data<-data[sage_vilaine,]

for (i in unique(data$annee_redevance))
{
data_i<-subset(data, annee_redevance==i)
  
table_id <- DBI::Id(schema = "r621_step",
                          table = paste0("flux_redevances_indus_annee_", i))

try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.flux_redevances_indus_annee_", i," (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(data_i)[colnames(data_i)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)

# Insérer l'objet sf dans la table postgis
sf::st_write(data_i, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.flux_redevances_indus_annee_", i," IS '{
  \"Title\": \"Flux annuels de pollution déclarés par les industriels assujettis à la redevance pollution de l’eau d’origine non domestique, sur le bassin Loire-Bretagne.\",
  \"Abstract\": \"Données extraites de https://donnees-documents.eau-loire-bretagne.fr/home/donnees/flux-de-pollution---industries.html pour le bassin Loire-Bretagne et importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"industrie\", \"assainissement\",\"redevance\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(data_i)$xmin,",
    \"ymin\": ",sf::st_bbox(data_i)$ymin,",
    \"xmax\": ",sf::st_bbox(data_i)$xmax,",
    \"ymax\": ",sf::st_bbox(data_i)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(data_i$annee_redevance),"\",
    \"End\": \"",max(data_i$annee_redevance),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://donnees-documents.eau-loire-bretagne.fr/home/donnees/flux-de-pollution---industries.html\"
  }]
}'"))

}



  return("OK")
}
