# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' importe_data_step
#'
#' @param dossier : adresse du dossier où sont stockés les fichiers csv exportés depuis le site 
#' https://www.assainissement.developpement-durable.gouv.fr/ 
#'
#' @return
#' statut de l'enregistrement des données (OK si les lignes ont été importées et KO sinon)
#' @export
#'
#' @examples
#'
#'   config <- yaml::read_yaml("C://workspace//gwilenalim//yaml//config.yml")
#'   dossier <- system.file(package = "gwilenalim")
#'   importe_data_step(dossier)
#'
importe_data_step <- function(dossier) {
  
  longitude_du_steu_wgs84<-latitude_du_steu_wgs84<-longitude_du_rejet_wgs84<-latitude_du_rejet_wgs84<-NULL
  data<-sage_vilaine<-annee<-code_du_steu<-nom_du_steu<-nature_du_steu<-etat_du_steu<-NULL
  date_de_mise_en_service_du_steu<-date_de_mise_hors_serv_du_steu<-capacite_nominale_en_eh<-NULL
  capacite_nominale_en_kg_de_dbo5<-debit_de_reference_en_m3_j<-filiere_eau_principale<-NULL
  filiere_boues_principale<-date_derniere_modification_steu<-nom_du_milieu_de_rejet<-NULL
  nom_du_bassin_versant<-niveau_traitement_existant_biologique<-niveau_traitement_existant_azote<-NULL
  niveau_traitement_existant_phosphore<-niveau_traitement_existant_desinfection<-type_de_reseau_majoritaire<-NULL
  code_de_masse_eau<-nom_de_la_masse_eau<-taille_agglomeration_eh<-tranche_obligation<-NULL
  charge_maximale_entrante_eh<-debit_entrant_en_m3_j<-percentile95_calcule_en_m3_j<-NULL
  conformite_globale_agglo<-cause_de_non_conformite<-conformite_equipement_agglo<-NULL
  conformite_en_performance_agglo<-conformite_collecte_agglo_temps_sec<-conformite_collecte_agglo<-NULL
  conformite_eru_perf_dbo<-conformite_eru_perf_dco<-conformite_eru_perf_ngl<-conformite_eru_perf_pt<-NULL
  prod_boues_sans_reactif_tms_an<-annee<-.<-NULL
  
  if (!is.character(dossier)) {stop("dossier should be character")}

# Établir la connexion à la base de données en utilisant les informations de connexion du fichier YAML
con <- DBI::dbConnect(RPostgres::Postgres(),
                      host = config$host,
                      port = config$port,
                      user = config$user,
                      password = config$password,
                      dbname = config$dbname)
  
  
#####TRAITEMENT DES FICHIERS PREALABLEMENT TELECHARGES #####  
  fichiers<-data.frame(nom=list.files(dossier, pattern = ".csv"),
                     chemin=list.files(dossier, pattern = ".csv", full.names=TRUE))


nettoyer_nom_colonne <- function(noms) {
  noms <- gsub("≥", "sup", noms)
  noms <- gsub("<", "inf", noms)
  noms <- gsub("%", "pc", noms)
  noms <- make.names(noms, unique = TRUE)
# Supprimer les suffixes ...n uniquement si cela ne crée pas de doublon
noms_sans_suffixe <- gsub("\\.\\.\\.[0-9]+$", "", noms)
# Identifier les doublons qui apparaîtraient après suppression
doublons <- duplicated(noms_sans_suffixe) | duplicated(noms_sans_suffixe, fromLast = TRUE)

# Conserver les noms originaux là où un doublon apparaîtrait
noms <- ifelse(doublons, noms, noms_sans_suffixe)
  noms <- gsub("é", "e", noms)
  noms <- gsub("è", "e", noms)
  noms <- gsub("à", "a", noms)
  noms <- gsub("ù", "u", noms)
  noms <- gsub("ç", "c", noms)
  noms <- gsub("[^[:alnum:]_]", "_", noms)
  noms <- gsub("__+", "_", noms)
 noms <- gsub("_$", "", noms)
  noms <- gsub(" ", "_", noms)
noms <- gsub("\"", "", noms)
noms <- gsub("\'", "_", noms)
noms <- gsub("\\/", "_", noms)
noms <- gsub("\\«", "", noms)
noms <- gsub("\\»", "", noms)
noms <- gsub("\\(", "", noms)
noms <- gsub("\\)", "", noms)
noms <- gsub("\\î", "i", noms)
noms <- gsub("\\\t", "_", noms)
noms <- gsub("\\:", "", noms)
noms <- gsub("__", "_", noms)
noms <- gsub("-", "_", noms)
  noms <- tolower(noms)
  noms <- substr(noms, 1, 63)
  
  return(noms)
}


lire_fichier <- function(i) {
  # Année extraite du nom du fichier
  annee <- substr(fichiers$nom[i], nchar(fichiers$nom[i])-7, nchar(fichiers$nom[i])-4)

 
# Lecture des noms de colonnes bruts
  noms_colonnes <- readLines(fichiers$chemin[i], n = 1, encoding = "UTF-8")
 noms_colonnes <- strsplit(noms_colonnes, "\\|")[[1]] # séparateur = barre verticale
noms_colonnes <- gsub('^"|"$', '', noms_colonnes) # supprimer les guillemets autour
noms_colonnes <- trimws(noms_colonnes)  # supprimer les espaces en trop

 # Lecture du fichier sans noms de colonnes
ajout <- readr::read_delim(
  fichiers$chemin[i],
  delim = "|",
  skip = 1,
  col_names = FALSE,
  quote = "\"",
  show_col_types = FALSE
)

names(ajout)<-noms_colonnes

correspondance_locale <- data.frame(
  original = noms_colonnes,
  postgis = nettoyer_nom_colonne(noms_colonnes),
  stringsAsFactors = FALSE
)


  problemes <- readr::problems(ajout)
if (nrow(problemes) > 0) {
  print(problemes)
}

    # Suppression des colonnes strictement doublonnées (même nom et même contenu)
ajout <- ajout[, !duplicated(as.list(ajout))]

names(ajout)<-nettoyer_nom_colonne(names(ajout))


# Harmonisation des noms de colonnes géographiques du STEU (2023 vs années précédentes)
if ("longitude_du_steu_wgs84" %in% names(ajout) == FALSE &&
    any(grepl("longitude.*steu.*wgs84", names(ajout)))) {
  names(ajout)[grepl("longitude.*steu.*wgs84", names(ajout))] <- "longitude_du_steu_wgs84"
}
if ("latitude_du_steu_wgs84" %in% names(ajout) == FALSE &&
    any(grepl("latitude.*steu.*wgs84", names(ajout)))) {
  names(ajout)[grepl("latitude.*steu.*wgs84", names(ajout))] <- "latitude_du_steu_wgs84"
}

# Harmonisation des noms de colonnes géographiques du rejet
if ("longitude_du_rejet_wgs84" %in% names(ajout) == FALSE &&
    any(grepl("longitude.*rejet.*wgs84", names(ajout)))) {
  names(ajout)[grepl("longitude.*rejet.*wgs84", names(ajout))] <- "longitude_du_rejet_wgs84"
}
if ("latitude_du_rejet_wgs84" %in% names(ajout) == FALSE &&
    any(grepl("latitude.*rejet.*wgs84", names(ajout)))) {
  names(ajout)[grepl("latitude.*rejet.*wgs84", names(ajout))] <- "latitude_du_rejet_wgs84"
}

# # homogénéisation des noms de colonnes 2023 et suivants par rapport à avant
#  names(ajout)[names(ajout) == "conformite_reglementaire_equipement_steu"] <- "conformite_eru_equipement_steu"
# names(ajout)[names(ajout) == "conformite_reglementaire_steu_perf_dbo"] <- "conformite_eru_steu_perf_dbo"
# names(ajout)[names(ajout) == "conformite_reglementaire_steu_perf_dco"] <- "conformite_eru_steu_perf_dco"
# names(ajout)[names(ajout) == "conformite_reglementaire_steu_perf_ngl"] <- "conformite_eru_steu_perf_ngl"
# names(ajout)[names(ajout) == "conformite_reglementaire_steu_perf_pt"] <- "conformite_eru_steu_perf_pt"
# names(ajout)[names(ajout) == "conformite_globale_steu_reglementaire_performances"] <- "conformite_globale_eru_performances"
# # on renseigne à "" les données qui n'existent plus à partir de 2023
# if(!"conformite_collecte_agglo_temps_sec" %in% names(ajout)){ajout$conformite_collecte_agglo_temps_sec<-""}
# if(!"date_mise_en_conformite_collecte_temps_sec" %in% names(ajout)){ajout$date_mise_en_conformite_collecte_temps_sec<-NA}  
  
  # Renommer les colonnes pour les rendre homogènes
  names(ajout)[names(ajout) == paste0("Etat de agglom\u00e9ration en ", annee)] <- "Etat_de_agglom\u00e9ration"
  names(ajout)[names(ajout) == paste0("Etat du STEU en ", annee)] <- "Etat_du_STEU"
  names(ajout)[names(ajout) == paste0("Conformit\u00e9 ERU \u00e9quipement STEU au 31/12/", annee)] <- "Conformit\u00e9_ERU_\u00e9quipement_STEU_au_31/12"
  names(ajout)[names(ajout) == paste0("Conformit\u00e9 ERU \u00e9quipement STEU pr\u00e9visionelle au 31/12/", annee)] <- "Conformit\u00e9_ERU_\u00e9quipement_STEU_pr\u00e9visionnelle_au_31/12"


  # Ajouter la colonne année
  ajout$annee <- annee

  return(list(ajout=ajout, correspondance=correspondance_locale))
}

# Lecture de tous les fichiers avec la mise en forme initiale
resultats_list <- purrr::map(seq_along(fichiers$nom), lire_fichier)

# Extraire les dataframes harmonisés
df_list <- purrr::map(resultats_list, "ajout")

# Extraire les correspondances de colonnes
correspondances_globales <- purrr::map(resultats_list, "correspondance")

# Fusionner toutes les correspondances en une seule table
correspondance_colonnes <- dplyr::bind_rows(correspondances_globales) %>%
  dplyr::distinct()


# Obtenir la liste complète des colonnes uniques à travers tous les fichiers
colonnes_completes <- purrr::reduce(purrr::map(df_list, names), union)

# Ajouter les colonnes manquantes dans chaque dataframe
df_list_harmonise <- purrr::map(df_list, function(df) {
  colonnes_manquantes <- setdiff(colonnes_completes, names(df))
  df[colonnes_manquantes] <- NA
  return(df)
})

# Fusionner les dataframes harmonisés
df_final <- dplyr::bind_rows(df_list_harmonise)


colonnes_geo <- c("longitude_du_steu_wgs84", "latitude_du_steu_wgs84", "longitude_du_rejet_wgs84", "latitude_du_rejet_wgs84")
colonnes_geo <- colonnes_geo[colonnes_geo %in% names(df_final)]

if (length(colonnes_geo) == 4) {
  df_final <- df_final %>%
    subset(!is.na(longitude_du_steu_wgs84) & !is.na(latitude_du_steu_wgs84)) %>%
    subset(!is.na(longitude_du_rejet_wgs84) & !is.na(latitude_du_rejet_wgs84))
} else {
  warning("Colonnes géographiques manquantes : ", paste(setdiff(c("longitude_du_steu_wgs84", "latitude_du_steu_wgs84", "longitude_du_rejet_wgs84", "latitude_du_rejet_wgs84"), colonnes_geo), collapse = ", "))
}



df_final$date_de_mise_hors_serv_du_steu[df_final$date_de_mise_hors_serv_du_steu=="1899-12-30"]<-NA

# renommage des noms de colonnes
# Fonction pour tronquer les noms de colonnes à 63 caractères
truncate_names <- function(names_vec) {
  substr(names_vec, 1, 63)
}

# Appliquer la fonction sur le dataframe
colnames(df_final) <- truncate_names(colnames(df_final))

# ajout de la colonne etat_du_steu
# Identifier les colonnes correspondant au motif
cols_to_concat <- grep("etat_du_steu", names(df_final), value = TRUE)


# Remplacer les NA par des chaînes vides
df_final[cols_to_concat] <- lapply(df_final[cols_to_concat], function(x) ifelse(is.na(x), "", x))

# Concaténer les valeurs ligne par ligne
df_final$etat_du_steu <- apply(df_final[cols_to_concat], 1, paste, collapse = "")

df_final<-df_final%>%dplyr::select(-dplyr::all_of(cols_to_concat))

df_sf <- sf::st_as_sf(df_final,
                      coords = c("longitude_du_steu_wgs84",
                                 "latitude_du_steu_wgs84"),
                      crs = 4326)
df_sf<-sf::st_transform(df_sf, crs=2154)
##### ENREGISTREMENT DU RESULTAT (DONNEES FR) DANS GEOGWILEN #####
table_id <- DBI::Id(schema = "m621_step",
                          table = "bdd_step_fr")

try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial



# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0(
  "CREATE TABLE m621_step.bdd_step_fr (",
  "id SERIAL PRIMARY KEY,",
  "geometry GEOMETRY,",
  paste(paste0("\"", colnames(df_sf)[colnames(df_sf) != "geometry"], "\" TEXT"), collapse = ", "),
  ")"
)


DBI::dbSendQuery(con, sql_create_table)

# Insérer l'objet sf dans la table postgis
sf::st_write(df_sf, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE m621_step.bdd_step_fr IS '{
  \"Title\": \"Stations d''épuration du bassin Loire-Bretagne\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne et importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(df_sf)$xmin,",
    \"ymin\": ",sf::st_bbox(df_sf)$ymin,",
    \"xmax\": ",sf::st_bbox(df_sf)$xmax,",
    \"ymax\": ",sf::st_bbox(df_sf)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(df_final$annee),"\",
    \"End\": \"",max(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))



  
##### Mise en forme des données sur BV Vilaine #####

##### donnees XY STEP ####
env <- new.env()
data("sage_vilaine", package = "gwilenalim", envir = env)

if (!"sage_vilaine" %in% ls(env)) {
  stop("L'objet 'sage_vilaine' n'a pas été trouvé dans le package.")
}

sage_vilaine <- env$sage_vilaine


sage_vilaine<-sf::st_transform(sage_vilaine, 2154)

df_sf<-df_sf[sage_vilaine,]%>%
  subset(annee==max(df_final$annee, na.rm=TRUE))%>%
  dplyr::select("code_du_steu")%>%
  unique()
df_sf$assainissement<-paste0("https://assainissement.developpement-durable.gouv.fr/pages/data/fiche-", 
                   df_sf$code_du_steu)


table_id <- DBI::Id(schema = "r621_step",
                          table = "r621_step_vilaine_xy_ste")

try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.r621_step_vilaine_xy_ste (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(df_sf)[colnames(df_sf)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)


# Insérer l'objet sf dans la table postgis
sf::st_write(df_sf, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.r621_step_vilaine_xy_ste IS '{
  \"Title\": \"Stations d''épuration du bassin de la Vilaine\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne, sélection sur le bassin de la Vilaine uniquement. Données importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(df_sf)$xmin,",
    \"ymin\": ",sf::st_bbox(df_sf)$ymin,",
    \"xmax\": ",sf::st_bbox(df_sf)$xmax,",
    \"ymax\": ",sf::st_bbox(df_sf)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(df_final$annee),"\",
    \"End\": \"",max(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))




##### donnees XY pt de rejet #####
df_sf_rej <- sf::st_as_sf(df_final%>%
    subset(annee==max(df_final$annee, na.rm=TRUE)), 
                      coords = c("longitude_du_rejet_wgs84", 
                                 "latitude_du_rejet_wgs84"), 
                      crs = 4326)

df_sf_rej<-sf::st_transform(df_sf_rej, crs=2154)
df_sf_rej<-df_sf_rej[sage_vilaine,]%>%
  dplyr::select("code_du_steu")%>%unique()

table_id <- DBI::Id(schema = "r621_step",
                          table = "r621_rejets_vilaine_xy_res")


try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.r621_rejets_vilaine_xy_res (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(df_sf_rej)[colnames(df_sf_rej)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)


# Insérer l'objet sf dans la table postgis
sf::st_write(df_sf_rej, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.r621_rejets_vilaine_xy_res IS '{
  \"Title\": \"Points de rejets au milieu naturel des stations d''épuration du bassin de la Vilaine\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne, sélection sur le bassin de la Vilaine uniquement. Données importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\", \"points de rejets\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(df_sf_rej)$xmin,",
    \"ymin\": ",sf::st_bbox(df_sf_rej)$ymin,",
    \"xmax\": ",sf::st_bbox(df_sf_rej)$xmax,",
    \"ymax\": ",sf::st_bbox(df_sf_rej)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(df_final$annee),"\",
    \"End\": \"",max(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))


##### donnees XY liaison STEP - pt de rejet #####

df_liaison<-df_final%>%
  subset(annee==max(df_final$annee, na.rm=TRUE))%>%
  dplyr::select("code_du_steu",
                "latitude_du_steu_wgs84",
                "longitude_du_steu_wgs84",
                "latitude_du_rejet_wgs84",
                "longitude_du_rejet_wgs84"
                )

names(df_liaison)<-c("code_du_steu",
                     "lon1",
                     "lat1",
                     "lon2",
                     "lat2")

    # creation shp_liaison STEP / pt rejet

    make_line <- function(lon1, lat1, lon2, lat2) {
      sf::st_linestring(matrix(c(lat1, lat2, lon1, lon2), 2, 2))
    }


    df_liaison <- df_liaison %>%
      dplyr::select(-`code_du_steu`) %>%
      purrr::pmap(make_line) %>%
      sf::st_as_sfc(crs = 4326) %>%
      sf::st_transform(crs=2154)%>%
      {
        tibble::tibble(`code_du_steu` = df_liaison$`code_du_steu`,
               geometry = .)
      } %>%
      sf::st_sf()


df_liaison<-sf::st_transform(df_liaison, crs=2154)
df_liaison<-df_liaison%>%
  subset(`code_du_steu` %in% df_sf$`code_du_steu` | 
           `code_du_steu` %in% df_sf_rej$`code_du_steu` )%>%unique()

table_id <- DBI::Id(schema = "r621_step",
                          table = "r621_liaison_steprejet_vilaine_xy_lis")

try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.r621_liaison_steprejet_vilaine_xy_lis (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(df_liaison)[colnames(df_liaison)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)


# Insérer l'objet sf dans la table postgis
sf::st_write(df_liaison, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.r621_liaison_steprejet_vilaine_xy_lis IS '{
  \"Title\": \"Liaison entre les stations d''épuration du bassin de la Vilaine et leurs points de rejet au milieu naturel\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne, sélection sur le bassin de la Vilaine uniquement. Données importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\", \"points de rejets\", \"liaison points de rejets\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(df_liaison)$xmin,",
    \"ymin\": ",sf::st_bbox(df_liaison)$ymin,",
    \"xmax\": ",sf::st_bbox(df_liaison)$xmax,",
    \"ymax\": ",sf::st_bbox(df_liaison)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(df_final$annee),"\",
    \"End\": \"",max(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))


##### table attributaire caractéristiques de la station r621_ouvrages_ous #####
df_final$filiere_eau_simplifiee <- ifelse(grepl("(?i)boue activée", df_final$filiere_eau_principale), "Boues activées",
                              ifelse(grepl("(?i)lagunage", df_final$filiere_eau_principale), "Lagunage",
                                     df_final$filiere_eau_principale))

names(df_final)[grepl("niveau", names(df_final))]

r621_ouvrages_ous<-df_final%>%
  dplyr::select(code_du_steu,
                nom_du_steu,
                nature_du_steu,
                etat_du_steu,
                date_de_mise_en_service_du_steu,
                date_de_mise_hors_serv_du_steu,
                capacite_nominale_en_eh,
                capacite_nominale_en_kg_de_dbo5,
                filiere_eau_principale,
                filiere_eau_simplifiee,
                filiere_boues_principale,
                date_derniere_modification_steu,
                nom_du_milieu_de_rejet,
                nom_du_bassin_versant,
                niveau_traitement_existant_biologique,
                niveau_traitement_existant_azote,
                niveau_traitement_existant_phosphore,
                niveau_traitement_existant_desinfection,
                niveau_traitement_requis_eru_biologique,
                niveau_traitement_requis_eru_azote,
                niveau_traitement_requis_eru_phosphore,
                type_de_reseau_majoritaire,
                code_de_masse_eau,
                nom_de_la_masse_eau,
                annee
                )%>%
  subset(`code_du_steu`%in% df_sf$`code_du_steu`)


r621_ouvrages_ous <- r621_ouvrages_ous %>%
  subset(is.na(date_de_mise_hors_serv_du_steu))%>%
  dplyr::group_by(code_du_steu) %>%
  dplyr::slice(which.max(annee)) %>%
  dplyr::ungroup()

r621_ouvrages_ous<-dplyr::left_join(df_sf, r621_ouvrages_ous, by="code_du_steu")



table_id <- DBI::Id(schema = "r621_step",
                          table = "r621_ouvrages_ous")


try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.r621_ouvrages_ous (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                            "annee NUMERIC,",
                           paste(paste0(colnames(r621_ouvrages_ous)[!colnames(r621_ouvrages_ous)%in%c("geometry",
                                                                                                  "annee")], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)

sql_commente_colonnes<-"COMMENT ON COLUMN r621_step.r621_ouvrages_ous.filiere_eau_simplifiee IS 'Filière de traitement des eaux avec regroupement par Eaux & Vilaine des différentes filières de type boues activées et des différentes filières de type lagunage';"
DBI::dbSendQuery(con, sql_commente_colonnes)



# Insérer l'objet sf dans la table postgis
sf::st_write(r621_ouvrages_ous, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.r621_ouvrages_ous IS '{
  \"Title\": \"Caractéristiques des stations d''épuration du bassin de la Vilaine\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne, sélection sur le bassin de la Vilaine uniquement. Données importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\", \"technologie de traitement\", \"boues activées\", \"lagunage\", \"filtre planté\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(r621_ouvrages_ous)$xmin,",
    \"ymin\": ",sf::st_bbox(r621_ouvrages_ous)$ymin,",
    \"xmax\": ",sf::st_bbox(r621_ouvrages_ous)$xmax,",
    \"ymax\": ",sf::st_bbox(r621_ouvrages_ous)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",max(df_final$annee),"\",
    \"End\": \"",max(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))


##### table attributaire conformité r621_conformite_cos #####
r621_conformite_cos<-df_final%>%
  dplyr::select(code_du_steu,
                nom_du_steu,
                annee,
                taille_agglomeration_eh,
                tranche_obligation,
                charge_maximale_entrante_eh,
                capacite_nominale_en_eh,
                debit_entrant_en_m3_j,
                percentile95_calcule_en_m3_j,
                conformite_globale_agglo,
                cause_de_non_conformite,
                conformite_equipement_agglo,
                conformite_en_performance_agglo,
                conformite_collecte_agglo_temps_sec,
                conformite_collecte_agglo,
                conformite_eru_steu_perf_dbo,
                conformite_eru_steu_perf_dco,
                conformite_eru_steu_perf_ngl,
                conformite_eru_steu_perf_pt,
                prod_boues_sans_reactif_tms_an
               )%>%
  subset(`code_du_steu`%in% df_sf$`code_du_steu`)%>%
  unique()

r621_conformite_cos<-dplyr::left_join(df_sf, r621_conformite_cos, by="code_du_steu")

table_id <- DBI::Id(schema = "r621_step",
                          table = "r621_conformite_cos")

#on efface la table préalablement à son remplissage (on ne peux pas écraser sinon on perd les vues dépendantes de la table)
try(DBI::dbRemoveTable(con, table_id))

# Créer une table postgis avec un index spatial

# Créer la requête SQL pour créer la table postgis
sql_create_table <- paste0("CREATE TABLE r621_step.r621_conformite_cos (",
                           "id SERIAL PRIMARY KEY,",
                           "geometry GEOMETRY,",
                           paste(paste0(colnames(r621_conformite_cos)[colnames(r621_conformite_cos)!="geometry"], " TEXT"), collapse = ", "),
                           ")")


DBI::dbSendQuery(con, sql_create_table)


# Insérer l'objet sf dans la table postgis
sf::st_write(r621_conformite_cos, 
             con, 
             table_id, 
             driver = "PostgreSQL", 
             append = TRUE)

# Commenter la table postgis

DBI::dbSendQuery(con, paste0("COMMENT ON TABLE r621_step.r621_conformite_cos IS '{
  \"Title\": \"Conformité des stations d''épuration du bassin de la Vilaine\",
  \"Abstract\": \"Données extraites de https://www.assainissement.developpement-durable.gouv.fr/ pour le bassin Loire-Bretagne, sélection sur le bassin de la Vilaine uniquement. Données importées sous geogwilen le ",format(Sys.Date(), "%d/%m/%Y"),"\",
  \"Keywords\": [\"station d''épuration\",\"STEP\", \"assainissement\", \"conformité\", \"performances épuratoires\", \"DERU\"],
  \"Categories\": [\"Données géographiques\"],
  \"SpatialExtent\": {
    \"xmin\": ",sf::st_bbox(r621_conformite_cos)$xmin,",
    \"ymin\": ",sf::st_bbox(r621_conformite_cos)$ymin,",
    \"xmax\": ",sf::st_bbox(r621_conformite_cos)$xmax,",
    \"ymax\": ",sf::st_bbox(r621_conformite_cos)$ymax,",
    \"srs\": \"EPSG:2154\"
  },
  \"TemporalExtent\": {
    \"Begin\": \"",min(df_final$annee),"\",
    \"End\": \"",min(df_final$annee),"\"
  },
  \"Contacts\": [{
    \"Name\": \"Anthony DE BURGHRAVE\",
    \"Email\": \"anthony.deburghrave@eaux-et-vilaine.bzh\"
  }],
  \"Links\": [{
    \"Type\": \"website\",
    \"URL\": \"https://www.assainissement.developpement-durable.gouv.fr/\"
  }]
}'"))

# fonction pour commenter les colonnes des bdd avec les noms d'origine
generer_commentaires <- function(con, schema, table, correspondance) {
  # Échapper les apostrophes dans les commentaires
  correspondance$original <- gsub("'", "''", correspondance$original)

  # Récupérer les noms de colonnes existants dans la table
  colonnes_base <- DBI::dbListFields(con, DBI::Id(schema = schema, table = table))

  # Filtrer les correspondances valides
  correspondance <- correspondance[correspondance$postgis %in% colonnes_base, ]

  # Générer les requêtes SQL COMMENT ON COLUMN
  commentaires <- paste0(
    "COMMENT ON COLUMN ", schema, ".", table, ".", correspondance$postgis,
    " IS '", correspondance$original, "';"
  )

  # Exécuter les requêtes avec dbExecute
  for (req in commentaires) {
    try(DBI::dbExecute(con, req), silent = TRUE)
  }
}




# Commentaire des colonnes des tables
generer_commentaires(con, "m621_step", "bdd_step_fr", correspondance_colonnes)
generer_commentaires(con, "r621_step", "r621_step_vilaine_xy_ste", correspondance_colonnes)
generer_commentaires(con, "r621_step", "r621_rejets_vilaine_xy_res", correspondance_colonnes)
generer_commentaires(con, "r621_step", "r621_liaison_steprejet_vilaine_xy_lis", correspondance_colonnes)
generer_commentaires(con, "r621_step", "r621_ouvrages_ous", correspondance_colonnes)
generer_commentaires(con, "r621_step", "r621_conformite_cos", correspondance_colonnes)



##### Fermer la connexion #####
DBI::dbDisconnect(con)

return(ifelse(nrow(df_final)>0, "OK", "KO"))
  
}
